### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pharaoh347** [Freddywhest/TimeFarmBot#6]
[2024-09-12 05:09:22] | ERROR | Unhandled error while receiving data
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
        read with ID 1294139288. Most likely, a TLObject was trying to be read when
         it should not be read. Remaining bytes: 500
    at BinaryReader.tgReadObject (/home/user1/TimeFarmBot/node_modules/telegram/extensions/BinaryReader.js:195:31)
    at VirtualClass.readResult (/home/user1/TimeFarmBot/node_modules/telegram/tl/api.js:451:35)
    at MTProtoSender._handleRPCResult (/home/user1/TimeFarmBot/node_modules/telegram/network/MTProtoSender.js:554:44)
    at MTProtoSender._processMessage (/home/user1/TimeFarmBot/node_modules/telegram/network/MTProtoSender.js:476:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/home/user1/TimeFarmBot/node_modules/telegram/network/MTProtoSender.js:424:17) {
  invalidConstructorId: 1294139288,
  remaining: <Buffer 98 ff 22 4d 01 00 00 00 31 f1 1e 3b c4 d6 3e 25 fe df 01 00 68 74 74 70 73 3a 2f 2f 74 69 6d 65 66 61 72 6d 2e 61 70 70 2f 23 74 67 57 65 62 41 70 70 ... 450 more bytes>
}
[2024-09-12 05:09:22] | ERROR | [timefarm] | | ❗Unknown error during Authorization: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be

**Comment by Nord1cWarr1or** [comment]
same.
This error also appeared in RockyRabbit

**Comment by Freddywhest** [comment]
Fixed
